config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/contact'
  get 'pages/services'
  get 'pages/tarifs'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def services
  end
  
  def tarifs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="text-center">
    <h2>Rejoignez-moi et écrivons ensemble notre histoire :</h2>
    <% if params[:action] != "home"%>
    <div class="principal">
      <ul class="list-inline text-center ">
        <li class='text-center'><%= mail_to "mikecoachsportif@gmail.com" do %>
        <i class="fa fa-envelope" aria-hidden="true"></i>
        <% end %></li>
        <li class='text-center'><i class="fa fa-phone-square" aria-hidden="true"></i></li>
      </ul>
      <% end %>
      <ul class="list-inline">
        <li><a href="https://www.instagram.com/mikecoach33/" target="_blank"><i class="fa fa-instagram"></i></a></li>
        <li><a href="https://www.facebook.com/mikecoach.fr" target="_blank"><i class="fa fa-facebook"></i></a></li>
      </ul>
      <h6 class="text-right grey">Mike Coach© 2016 Tout droit réservé.</h6>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--favicon -->
    <%= favicon_link_tag 'favicon.ico' %>
    <!-- end -->
    <title>MikeCoach</title>
    <%= csrf_meta_tags %>
    <!-- google referencement -->
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Mike Coach : Votre coach sportif personnel à Bordeaux </title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="copyright" content=">Mike Coach© 2016 Tout droit réservé"/>
    <meta name="description" content="Perte de poids, Conseils en nutrition / Rééquilibrage alimentaire, Renforcement musculaire / tonification,Prise de masse
    ,Préparation physique,Rééducation post-traumatique,Coaching enfants-ados (8-16 ans),Coaching à distance,Cross-training"/>
    <meta name="keywords" content="coach, bordeaux, coaching personnel, sport" />
    <meta name="robots" content="index,follow"/>
    <meta name="DC.title" content="MikeCoach" />
    <!-- end -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/scrollreveal@3.3.2/dist/scrollreveal.min.js"></script>
    <!-- google-analytics -->
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-89537772-1', 'auto');
    ga('send', 'pageview');
    </script>

    <!-- facebook pub -->
    <meta property="og:url"                content="http://mikecoach.fr/" />
    <meta property="og:type"               content="Website" />
    <meta property="og:title"              content="Mike Coach : Votre coach sportif personnel à Bordeaux " />
    <meta property="og:description"        content="Perte de poids, Conseils en nutrition / Rééquilibrage alimentaire, Renforcement musculaire / tonification,Prise de masse
                                                    ,Préparation physique,Rééducation post-traumatique,Coaching enfants-ados (8-16 ans),Coaching à distance,Cross-training" />
    <meta property="og:image"              content="mikecoach09" />
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>

</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="banner-home " style="background-image: url('<%= image_path 'happy.jpg' %>');">
  <div class="banner-content">
    <h1>Coach sportif personnel</h1>
    <hr>
    <h2>Le goût du sport ensemble</h2>
  </div>
</div>

<div class="text-center padded ">
  <h1>Qui suis-je ?</h1>
  <br>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-6 mov_left">
        <%= image_tag 'mikecoach15.png'%>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 text-left mov_right">
        <p>Passionné par le sport et dynamisé par les rapports humains, devenir coach sportif a été pour moi une évidence. Donner, recevoir et partager sont, au-delà des valeurs fondamentales de ma vie, le reflet de mon travail et de ce que nous vivrons ensemble durant les coachings. </p>
        <p>A domicile ou en extérieur, tous les terrains d'entraînement sont possibles pour atteindre ensemble vos objectifs. Soucieux de répondre parfaitement à vos attentes, je personnalise chacune de mes séances pour qu'elle ne ressemble qu'à vous.</p>
        <p>Installé près de Bordeaux, je vous propose mes services de la Métropole jusqu'au Bassin d'Arcachon, de manière individuelle tant pour les adultes que pour les enfants et les adolescents.</p>
        <p>Ma formation, mon professionnalisme et mon énergie associés à votre motivation, votre volonté et votre implication seront les clés de votre réussite. Je m'y engage personnellement et vous attends dès à présent pour  vivre ensemble de beaux défis sportifs.</p>
      </div>
    </div>
  </div>
</div>


<div class="text-center wrapper-grey">
    <h1>Services</h1>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-3 col-md-3 foo">
        <%= link_to pages_services_path do %>
        <%= image_tag 'Mike_emma.jpg', class:"image-circle"%>
        <% end %>
        <h3>Coaching personnel</h3>
      </div>
      <div class="col-xs-12 col-sm-3 col-md-3 foo2">
        <%= link_to image_tag('mikecoach06.jpg',class:"image-circle"), pages_services_path(:anchor => "anchor") %>
        <h3>Coaching enfants-ados</h3>
      </div>
      <div class="col-xs-12 col-sm-3 col-md-3 foo3">
        <%= link_to image_tag('mikecoach01.jpg',class:"image-circle1"), pages_services_path(:anchor => "anchor2") %>
        <h3>Coaching à distance</h3>
      </div>
      <div class="col-xs-12 col-sm-3 col-md-3 foo4">
        <%= link_to image_tag('mikecoach14.jpg',class:"image-circle"), pages_services_path(:anchor => "anchor3") %>
        <h3>Cross-training</h3>
      </div>
    </div>
  </div>
</div>

<div class="text-center wrapper-white">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 foo">
        <div class="text-center">
          <p>Chaque jour est une nouvelle chance.
            Le regard tourné vers l'avenir, oublions vos excuses et défions vos limites.
            Il n'y a pas de grandes ou de petites victoires, il n'en existe que des belles : les vôtres.</p>
        </div>
      </div>
      <div class=" text-right">
        <div class="col-xs-12 col-sm-12  col-md-12">
          <p class="toto">Mike Coach<p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="banner_down" style="background-image: url('<%= image_path 'mountain-help-dpc.png'%>');">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-12 col-md-offset-0 foo">
        <h1>Votre coach sportif personnel</h1>
          <div class="list-inline ">
            <li class='text-center'><%= mail_to "mikecoachsportif@gmail.com" do %>
            <i class="fa fa-envelope" aria-hidden="true"></i>
            <% end %>
            <p>mikecoachsportif@gmail.com</p></li>
            <li class='text-center'><i class="fa fa-phone-square" aria-hidden="true"></i>
            <p class= "number">06 26 88 22 66</p></li>
          </div>
        </div>
          <!-- <div class="col-xs-12 col-md-3 col-md-offset-9 text-right foo ">
            <h4>l'homme qui déplace une montagne commence par déplacer des petites pierre</h4>
            <p class="text-right">Confucius</p>
          </div> -->
    </div>
  </div>
</div>

app/views/pages/modal/_modal1Service.html.erb
<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="padded_service">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
              <%= image_tag 'happy.jpg'%>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
              <h2>Perte de poids<h2>
              <p>Une fois n'est pas coutume, si vous voulez perdre du poids, le sport sera votre meilleur allié.
                  Inutile de vous contraindre à des privations alimentaires excessives, il a déjà été prouvé trop souvent que le résultat de ces pratiques n'est que frustration et inefficacité sur le long terme. C'est pourquoi je vous propose un programme sportif 100% personnalisé, accompagné des conseils alimentaires nécessaires pour vous offrir des résultats durables et bien meilleurs pour votre santé.
                  Au-delà de l'aspect sportif et nutritionnel, mon rôle sera aussi de vous accompagner et de vous motiver à chaque étape de votre parcours. Ainsi, pas à pas, nous ferons pencher ensemble la balance du bon côté : c'est en tout cas le défi que je vous invite à relever.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/modal/_modal2Service.html.erb
<div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="padded_service2">
        <div class="container">
          <div class="row">
            <div class="col-sx-12 col-sm-6 col-md-6">
              <h2>Conseils en nutrition / Rééquilibrage alimentaire<h2>
              <p>Trouver un juste équilibre, prendre en masse musculaire, perdre quelques kilos superflus : tels sont les différents enjeux d'un rééquilibrage alimentaire.
              Pour cela, je mets mes connaissances à votre service pour vous conseiller sur votre alimentation quotidienne, l'objectif ici n'étant pas de vous faire manger moins mais au contraire de vous faire manger mieux.
              De manière générale, avoir une bonne hygiène de vie contribue à nous maintenir en bonne santé. Cela est d'autant plus vrai pour les personnes qui pratiquent une activité physique : il est alors indispensable de fournir à votre corps les bons aliments aux bons moments pour renouveler votre énergie et ne pas vous épuiser inutilement.
              </p>
            </div>
            <div class="col-sx-12 col-sm-6 col-md-6">
              <%= image_tag 'happy.jpg'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/modal/_modal3Service.html.erb
<div class="modal fade" id="modal3" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="padded_service">
        <div class="container">
          <div class="row">
            <div class="col-sx-12 col-sm-6 col-md-6">
              <%= image_tag 'happy.jpg'%>
            </div>
            <div class="col-sx-12 col-sm-6 col-md-6">
              <h2>Renforcement musculaire / tonification<h2>
              <p>Envie de tonifier votre corps, sculpter votre silhouette, perdre de la masse grasse : cette méthode est faite pour vous, le but étant de faire travailler l'ensemble de vos muscles en profondeur, sur une même séance d'entraînement.
                 Au-delà de la motivation esthétique qui est souvent énoncée dans ce cadre-là, le renforcement musculaire permet également de prévenir certaines blessures ou traumatismes notamment par le gainage du corps, le renforcement des articulations, le gain cardio-vasculaire et l'augmentation de la force physique que cela induit.
                 Parce que ce travail sur vous-même peut largement contribuer à votre bien-être quotidien et futur, je vous invite à vous laisser tenter : vous ne pourrez bientôt plus vous en passer.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/modal/_modal4Service.html.erb
<div class="modal fade" id="modal4" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="padded_service2">
        <div class="container">
          <div class="row">
            <div class="col-sx-12 col-sm-6 col-md-6">
              <h2>Prise de masse<h2>
              <p>Adepte de musculation ou complexé(e) par votre silhouette que vous jugez trop fine, vous souhaitez focaliser vos efforts sur la prise de masse et de volume. Pour cela, nous allons travailler ensemble autour de deux aspects fondamentaux : l'exécution d'exercices ciblés ET la manière de vous nourrir.
                 En effet, avant de vous engager dans cette perspective, sachez que l'alimentation a un rôle très important pour accroître votre masse musculaire efficacement. Ainsi, il sera important de mettre en place un programme adapté à vos objectifs bien sûr, mais aussi à vous-même et à votre morphologie.
              </p>
            </div>
            <div class="col-sx-12 col-sm-6 col-md-6">
              <%= image_tag 'happy.jpg'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/modal/_modal5Service.html.erb
<div class="modal fade " id="modal5" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="padded_service">
        <div class="container">
          <div class="row">
            <div class="col-sx-12 col-sm-6 col-md-6">
              <%= image_tag 'happy.jpg'%>
            </div>
            <div class="col-sx-12 col-sm-6 col-md-6">
              <h2>Préparation physique<h2>
              <p>Une compétition à venir, un défi sportif à relever, un objectif personnel à atteindre : il est indispensable de vous y préparer pour optimiser votre réussite. C’est en tout cas ce que je vous propose par des entraînements ciblés et un accompagnement 100% personnalisé.
                 Investi sur un programme de plusieurs semaines, je m'engage à mettre mes compétences au service de vos ambitions. Ajoutées à cela votre motivation, votre volonté et votre assiduité dans le travail pour que notre collaboration soit le début de votre succès.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/modal/_modal6Service.html.erb
<div class="modal fade" id="modal6" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="padded_service2">
        <div class="container">
          <div class="row">
            <div class="col-sx-12 col-sm-6 col-md-6">
              <h2>Rééducation post-traumatique</h2>
              <p>Une opération, un accident, un choc, un traumatisme : vous vous retrouvez immobilisé(e) pendant une durée plus ou moins longue.
                 Une fois votre guérison assurée, une reprise du sport en douceur est alors essentielle pour consolider votre état de santé et retrouver des sensations peut-être oubliées. C'est ici que j'interviens en vous proposant des exercices de base, simples et faciles à réaliser, qui évolueront au rythme de votre progression personnelle, sans jamais vous brusquer, mais précisément sélectionnés pour mettre en lumière l'étendue de vos capacités.
                 (Pour votre sécurité, demandez l'avis de votre médecin avant de débuter la pratique d'une activité sportive)
              </p>
            </div>
            <div class="col-sx-12 col-sm-6 col-md-6">
              <%= image_tag 'happy.jpg'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/modal/_modal7Service.html.erb
<div class="modal fade" id="modal7" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="padded_service">
        <div class="container">
          <div class="row">
            <div class="col-sx-12 col-sm-6 col-md-6">
              <%= image_tag 'happy.jpg'%>
            </div>
            <div class="col-sx-12 col-sm-6 col-md-6">
              <h2>Circuit-training</h2>
              <p>Vous êtes timide, réservé(e). Vous voudriez bien faire du sport, mais vous êtes seul(e) et pas toujours très motivé(e). Pas de problème, j'ai la solution pour vous sortir du canapé.
                 En semaine et le week-end, je vous propose de nous retrouver en petit comité, pour s’entraîner de manière ludique et variée, à travers des parcours sportifs fréquemment renouvelés. L'intérêt principal de ce concept relève de la mixité des activités qui sont proposées au cours d'une même séance (exemple : course à pied, pompes, tractions, abdominaux, corde à sauter).
                 Les circuits-training peuvent se pratiquer en intérieur (salle de sport), comme en extérieur (parcs) selon la météo et les envies du moment. Cette méthode est accessible à tous, elle permet d'améliorer considérablement votre condition physique générale tout en vous offrant de beaux moments d'entraide et de partage dans l'effort.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/modal/_modal8Service.html.erb
<div class="modal fade" id="modal8" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="padded_service2">
        <div class="container">
          <div class="row">
            <div class="col-sx-12 col-sm-6 col-md-6">
              <h2>Coaching enfants-ados (8-16 ans)</h2>
              <p>Animateur sportif pendant 10 ans dans les écoles élémentaires, il était important pour moi d'intégrer à mes coachings des formules pour les enfants et les adolescents. La manière de travailler est, certes, un peu différente mais les objectifs sont souvent les mêmes que pour les adultes (perte de poids, tonification, rééducation post-traumatique...).
                 Aussi, à l'âge où votre enfant se construit, il est parfois difficile pour lui de trouver sa place au sein d'un collectif et/ou d'éprouver du plaisir dans une activité spécifique. C'est ici que j'interviens en lui proposant des exercices ludiques et variés dans lesquels il pourra pleinement s'épanouir et trouver sa propre voie.
                 Pour les adolescents, la puberté n'est pas toujours très bien vécue par certains(es) en raison des transformations physiques qu'elle génère. Il est alors bon d'avoir à ce moment-là un soutien extérieur, un accompagnement personnalisé, afin d'apprivoiser ce nouveau corps et se sentir, dès lors, mieux dans sa peau.
                 Empli de passion pour ces jeunes gens, je mettrai tout mon cœur à l'ouvrage pour qu'ensemble nous menions à bien chacune de ces missions.
              </p>
            </div>
            <div class="col-sx-12 col-sm-6 col-md-6">
              <%= image_tag 'happy.jpg'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/modal/_modal9Service.html.erb
<div class="modal fade" id="modal9" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="padded_service">
        <div class="container">
          <div class="row">
            <div class="col-sx-12 col-sm-6 col-md-6">
              <%= image_tag 'happy.jpg'%>
            </div>
            <div class="col-sx-12 col-sm-6 col-md-6">
              <h2>Coaching à distance</h2>
              <p>Manque de temps, complexes, isolement géographique : vous avez envie de vous prendre en main mais cela vous paraît impossible. Il est temps pour vous de vous détendre et de me faire confiance.
                Je vous invite tout d'abord à me contacter par téléphone pour déterminer la nature de vos besoins. Ainsi, je pourrai rapidement vous faire parvenir par mail votre programme sportif détaillé comprenant les différents exercices à réaliser, les consignes d'exécution à respecter (placements, respiration, sécurité) ainsi que les conseils alimentaires susceptibles de vous aider.
                Afin de vous garantir un suivi personnalisé, des bilans réguliers vous seront proposés pour évaluer votre progression, vos points forts ainsi que les axes de travail à poursuivre et/ou à améliorer selon les objectifs que nous nous serons fixés. 
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h1 class="title_home"><%= image_tag "logo.png", class:"logo"%> Mike Coach<h1>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm" >
      <a><%= link_to t("Accueil"), root_path, class: "navbar-wagon-item navbar-wagon-link" %></a>
      <%= link_to t("Services"), pages_services_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t("Tarifs"), pages_tarifs_path, class: "navbar-wagon-item navbar-wagon-link" %>
  </div>
    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to t("Accueil"), root_path%></li>
          <li><%= link_to t("Services"), pages_services_path%></li>
          <li><%= link_to t("Tarifs"), pages_tarifs_path%></li>
        </ul>
      </div>
    </div>
  </div>